### ISSUE TITLE
Inclusion into Net-HTTP-Spore proper

### ISSUE THREAD

**Issue by a3f** [gempesaw/Net-HTTP-Spore-Middleware-Format-Text#1]
Hello,

I just pushed version 0.08 of Net::HTTP::Spore which includes your pull request [that added this module](https://github.com/SPORE/net-http-spore/commit/914744d44c0d6520b7778a2394dc37c5e7cd49e4):

```
Status: Permission missing
==========================

    module : Net::HTTP::Spore::Middleware::Format::Text
    version: 0.08
    in file: Net-HTTP-Spore-0.08/lib/Net/HTTP/Spore/Middleware/Format/Text.pm
    status : Not indexed because permission missing. Current registered
            primary maintainer is GEMPESAW. Hint: you can always find
            the legitimate maintainer(s) on PAUSE under "View
            Permissions".
```

How should we handle this? Should I drop the text frontend from the distribution or do you prefer to take down your module in favor of having both in a single distribution?

**Comment by gempesaw** [comment]
oh! yeah, if you're willing, I'm happy to cede control of the name Net::HTTP::Spore::Middleware::Format::Text back over to y'all so it's all in the single distribution. Uhh, I'll try to figure out how to do that in PAUSE...

edit: ok i think i gave you primary, do you think it will work now?

![image](https://user-images.githubusercontent.com/1437272/32109677-5ea1ebd0-bb03-11e7-922c-cd670d6de79f.png)

**Comment by a3f** [comment]
I just forced a reindexing and it is resolved:
```
     module : Net::HTTP::Spore::Middleware::Format::Text
     version: 0.09
     in file: Net-HTTP-Spore-0.09/lib/Net/HTTP/Spore/Middleware/Format/Text.pm
     status : indexed
```
Searching for `Net::HTTP::Spore::Middleware::Format::Text` gives me `Net::HTTP::Spore`. Thanks!
